apiVersion: v1
kind: DeploymentConfig
metadata:
  name: ${project.artifactId}
spec:
  replicas: 1
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_DIR
          value: /deployments
        - name: SSO_AUTH_SERVER_URL
          value: ${SSO_AUTH_SERVER_URL}
        - name: SSO_AUTH_CLIENT_SECRET
          value: ${SSO_AUTH_CLIENT_SECRET}
        - name: JAVA_OPTIONS
          value: -Dsso.auth.server.url=${SSO_AUTH_SERVER_URL} -Dsso.clientSecret=${SSO_AUTH_CLIENT_SECRET} -Dswarm.project.stage.file=file:///deployments/config/clarksnut-stages.yml -Dswarm.project.stage=production-peru
        name: ${project.artifactId}
        image: ${project.artifactId}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        securityContext:
          privileged: false
        volumeMounts:
        - name: clarksnut-mail-collector-config
          mountPath: /deployments/config
      volumes:
      - name: clarksnut-mail-collector-config
        secret:
          secretName: clarksnut-mail-collector-config
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - ${project.artifactId}
      from:
        kind: ImageStreamTag
        name: ${project.artifactId}:latest
    type: ImageChange
