apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: clarksnut-mail-collector
    labels:
      app: clarksnut-mail-collector
  data:
    cn.mail.vendor.gmail.applicationName: "Clarsknut"
    cn.scheduler.send.size: "50"
    cn.scheduler.pull.internal: "600"
    cn.document.apiUrl: "http://localhost:8080/api/documents"