apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    name: clarksnut-config
    labels:
      app: clarksnut
  data:
    clarksnut-stages.yml: bG9nZ2VyOgogIGxldmVsOiBERUJVRwpzd2FybToKICBkYXRhc291cmNlczoKICAgIGRhdGEtc291cmNlczoKICAgICAgQ2xhcmtzbnV0RFM6CiAgICAgICAgZHJpdmVyLW5hbWU6IHBvc3RncmVzcWwKICAgICAgICB1c2VyLW5hbWU6IGNsYXJrc251dAogICAgICAgIHBhc3N3b3JkOiBjbGFya3NudXQKICAgICAgICBjb25uZWN0aW9uLXVybDogamRiYzpwb3N0Z3Jlc3FsOi8vY2xhcmtzbnV0LW1haWwtY29sbGVjdG9yLWRiOjU0MzIvY2xhcmtzbnV0CmNsYXJrc251dDoKICBtYWlsOgogICAgdmVuZG9yOgogICAgICBnbWFpbDoKICAgICAgICBhcHBsaWNhdGlvbk5hbWU6ICJDbGFya3NudXQiCiAgc2NoZWR1bGVyOgogICAgcHVsbDoKICAgICAgaW50ZXJ2YWw6IDM2MDAKICAgIHNlbmQ6CiAgICAgIHNpemU6IDUwCi0tLQpwcm9qZWN0OgogIHN0YWdlOiBwcm9kdWN0aW9uCmNsYXJrc251dDoKICBkb2N1bWVudDoKICAgIGFwaVVybDogImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvZG9jdW1lbnRzIg==
