apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    name: clarksnut-mail-collector-config
    labels:
      app: clarksnut-mail-collector
  data:
    clarksnut-stages.yml: cHJvamVjdDoKICBzdGFnZTogcHJvZHVjdGlvbi1wZXJ1CnN3YXJtOgogIGRhdGFzb3VyY2VzOgogICAgZGF0YS1zb3VyY2VzOgogICAgICBDbGFya3NudXREUzoKICAgICAgICBkcml2ZXItbmFtZTogcG9zdGdyZXNxbAogICAgICAgIHVzZXItbmFtZTogY2xhcmtzbnV0CiAgICAgICAgcGFzc3dvcmQ6IGNsYXJrc251dAogICAgICAgIGNvbm5lY3Rpb24tdXJsOiBqZGJjOnBvc3RncmVzcWw6Ly9jbGFya3NudXQtbWFpbC1jb2xsZWN0b3ItZGI6NTQzMi9jbGFya3NudXQKY2xhcmtzbnV0OgogIG1haWw6CiAgICB2ZW5kb3I6CiAgICAgIGdtYWlsOgogICAgICAgIGFwcGxpY2F0aW9uTmFtZTogIkNsYXJrc251dCIKICBzY2hlZHVsZXI6CiAgICBwdWxsOgogICAgICBpbnRlcnZhbDogMzYwMAogICAgc2VuZDoKICAgICAgc2l6ZTogNTAKICBkb2N1bWVudDoKICAgIGFwaVVybDogImh0dHA6Ly9jbGFya3NudXQtY2xhcmtzbnV0LmFwcHMuY29uc29sZS5zaXN0Y29vcC5vcmcvYXBpL2RvY3VtZW50cyIKICAgIGFkZGl0aW9uYWxUeXBlc1N1cHBvcnRlZDogIlBlcmNlcHRpb24sIFJldGVudGlvbiwgVm9pZGVkRG9jdW1lbnRzLCBTdW1tYXJ5RG9jdW1lbnRzIgo=