apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: clarksnut-mail-collector
    labels:
      app: clarksnut-mail-collector
  type: Opaque
  data:
    db.user: "Y2xhcmtzbnV0"
    db.password: "Y2xhcmtzbnV0"
    db.admin.password: "Y2xhcmtzbnV0"